### ISSUE TITLE
Not found popup

### ISSUE THREAD

**Issue by narutojawad** [Catogram/Catogram#104]
Greetings, 

There a "not found" popup that comes every time I launch the app. 

(Last update) 
![Screenshot_20210504-094716__01](https://user-images.githubusercontent.com/7191239/116969218-8fb99500-acbe-11eb-8570-029e58774f02.jpg)

**Comment by sudo-nautilus** [comment]
@narutojawad https://user-images.githubusercontent.com/7191239/116969218-8fb99500-acbe-11eb-8570-029e58774f02.jpg

**Comment by sudo-nautilus** [comment]
@narutojawad It comes because it cant find new updates,
Everyone is facing it 😳

**Comment by ctwoon** [comment]
@narutojawad It writes 'not found' because it can't found any update. Temporarily solution is disabling auto-updates check. I'll rework this part later.

**Comment by sudo-nautilus** [comment]
@ctwoon Where is disable auto updates ?

**Comment by ctwoon** [comment]
@sudo-nautilus catogram settings > updates > toggle

**Comment by sudo-nautilus** [comment]
@ctwoon Thanks found it
