### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by Subbarao6338** [Catogram/Catogram#150]
Please add following features

Hide my phone number.
Translate chats.
Show ID in profile.
Small sticker sizes.
Add tab folders to bottom.

![](https://i.imgur.com/veeb9YA.jpg)
![](https://i.imgur.com/5kZGOSQ.jpg)
![](https://i.imgur.com/hcqwzPA.jpg)

**Comment by ctwoon** [comment]
what is that

you aren't using Catogram lol

**Comment by iTaysonLab** [comment]
@Subbarao6338 Sorry, but Catogram has these features)

**Comment by Subbarao6338** [comment]
What about bottom tabs?

**Comment by ctwoon** [comment]
> What about bottom tabs?

not going to be implemented

**Comment by Subbarao6338** [comment]
@ctwoon why?
It's useful for larger screens

**Comment by Subbarao6338** [comment]
I didn't find storage location options and backup settings option

**Comment by ctwoon** [comment]
@Subbarao6338 1) catogram settings -> security
2) not exists yet.

**Comment by xerix123456** [comment]
@ctwoon why

**Comment by ctwoon** [comment]
@xerix123456 because there's literally no matter where folders located since you changing them by swipe.
