### ISSUE TITLE
Notifications without sound

### ISSUE THREAD

**Issue by Kako121** [Catogram/Catogram#160]
Hi all,

I just installed Catogram and I really liked it, but I have a little problem:
Notifications arrive... but the phone does not emit any sound, it just vibrates (The sounds are activated, and in the other applications it works correctly).

My phone is a xiaomi Redmi 5+ (Android 8.1) with the latest version of Catogram (today).

Do you know how to solve it?
Thanks

**Comment by ctwoon** [comment]
@Kako121 Hello, it sounds like your OEM firmware problem.

**Comment by Kako121** [comment]
Wow, that's a shame.

Well the rest of things seems to work all ok.
I will leave Catogram installed!

Thanks!

> @Kako121 Hello, it sounds like your OEM firmware problem.

**Comment by ctwoon** [comment]
@Kako121 Nice decision.
