### ISSUE TITLE
[Feature Request] Ignore hashtags

### ISSUE THREAD

**Issue by PiRomant** [Catogram/Catogram#161]
Hide (or don't notify) messages with hashtag from ignore list

**Comment by ctwoon** [comment]
against telegram api TOS. 

1.4. It is forbidden to interfere with the basic functionality of Telegram. This includes but is not limited to: making actions on behalf of the user without the user's knowledge and consent, preventing self-destructing content from disappearing, preventing last seen and online statuses from being displayed correctly, tampering with the 'read' statuses of messages (e.g. implementing a 'ghost mode'), preventing typing statuses from being sent/displayed, etc.
