### ISSUE TITLE
[Feature request] filter chats and publics in folder settings

### ISSUE THREAD

**Issue by AppOfizzz** [Catogram/Catogram#164]
The ability to filter out publics and chats how to are in the screenshot below. Add, for example, a filter such as "not in folder". 
![Screenshot_20210817-005056_1](https://user-images.githubusercontent.com/80394374/129635141-74c0d11b-86ca-482f-9069-0d739b5d072a.png)

**Comment by ctwoon** [comment]
@AppOfizzz

**Comment by AppOfizzz** [comment]
> @AppOfizzz

?
