### ISSUE TITLE
能不能添加用节点当代理的功能

### ISSUE THREAD

**Issue by CitizenScyu** [Catogram/Catogram#165]
很需要把节点当做代理的功能，现在只有nekox有这个功能。

**Comment by ios7jbpro** [comment]
@CitizenScyu

**Comment by ios7jbpro** [comment]
@ios7jbpro no bruh

**Comment by ctwoon** [comment]
I don't understand this language, nor the translator allow me to understand what you wrote.

**Comment by ctwoon** [comment]
no response. closed.
