### ISSUE TITLE
Crash edit msg

### ISSUE THREAD

**Issue by TOWUK** [Catogram/Catogram#175]
Latest build catogram.
Join chat, send msg and edit it!

**Comment by TOWUK** [comment]
How chat dont access?
![Uploading Screenshot_20210922-175040.png…]()

**Comment by TOWUK** [comment]
![Screenshot_20210922-175040](https://user-images.githubusercontent.com/28830162/134367986-dce1c819-f33b-4034-b0a2-fc7f3454f35f.png)

**Comment by ctwoon** [comment]
known issue, read channel

**Comment by groozchique** [comment]
@TOWUK
