### ISSUE TITLE
Catogram crash

### ISSUE THREAD

**Issue by davidj77** [Catogram/Catogram#176]
Hi, Cato 3.9.5 is crashing when I try to joint to @IranintlTV live stream.

![Screenshot_20210924-132529](https://user-images.githubusercontent.com/71226185/134723510-08521587-84f8-4460-b5c6-93bc5a029009.png)
I'm using a Samsung sm-j700m
Armeabi-v7a
Android 6.0.1
Official tg works fine when I joint to this live stream.
Thanks in advance.

**Comment by cactus889** [comment]
@davidj77 что?

**Comment by Mojiberus** [comment]
@davidj77 Lmao, ok

**Comment by ctwoon** [comment]
can't reproduce
