### ISSUE TITLE
[Q] When will be available in F-Droid?

### ISSUE THREAD

**Issue by mizzunet** [Catogram/Catogram#47]
So, it will more people know about Catogram became OSS and yeah updating app becomes easier.

**Comment by iTaysonLab** [comment]
FDroid has a very complicated mechanism of submitting applications.

Also, CG uses Google's FCM, which is not so good for them.

**Comment by ctwoon** [comment]
@mizzunet Won't be as catogram won't work properly without GCM. Also, it requires additional amount of time for maintaining it, which we don't have.

**Comment by mizzunet** [comment]
I see
