### ISSUE TITLE
[Issue] Emoji are bigger than the keyboard (with the option "Use system emoji" enabled)

### ISSUE THREAD

**Issue by r3mis** [Catogram/Catogram#48]
**Hi,**

If you enable the "Use system emoji" option from the Catogram settings, the Emoji Keyboard will be displayed in a wrong way. 
Picture:
![image](https://user-images.githubusercontent.com/52204908/106559782-378bbf00-6526-11eb-82ed-abc1a9ff0a4e.png)
_(thanks to herr cyrex on Telegram)_

Tested this by myself, too. It occurs on both Android 11 and Android 10. Didn't tested on other Android versions.

**Comment by ctwoon** [comment]
Fixed.
