### ISSUE TITLE
[Feature] Using Markdown for Hyperlinks

### ISSUE THREAD

**Issue by r3mis** [Catogram/Catogram#51]
In Markdown, Hyperlinks can be applied to a text by using [] and ().
An example can be:
`[test](google.com)`
This won't work on Telegram, sadly.

My question was: is possible to add this on Catogram? It's a good idea, in my opinion. People won't have anymore to select the text, click this, click that etc. etc. yada yada, but just to use [] and (). Simple, no?

**Comment by ctwoon** [comment]
won't be added. current implementation is more than fine.
