### ISSUE TITLE
Catogram does not respect the system font for CJK

### ISSUE THREAD

**Issue by Raymonf** [Catogram/Catogram#60]
(This is actually DrKLO's fault like everything else btw)

I'm not sure how familiar you/the developer are with CJK (basically East Asian characters), so I'll give a quick rundown:

When the system is set to a Chinese, Japanese, or Korean, the system automagically switches to the proper glyphs within the bundled Noto Sans CJK fonts for the proper locale.

This is because each area has some slightly different conventions for writing characters--especially kanji characters. So, if my system language is zh-HK, I expect to see glyphs that follow the (less than amazing, but better than China's) Hong Kong standard.

Right now, Catogram and Telegram just use zh-CN (or China's glyphs) though I'm not really sure why. Plus Messenger and TGX handle this correctly. The "use system font" toggle does not seem to fix this.

Would you be willing to look into this?

**Comment by Raymonf** [comment]
I did some more research. I think this occurs due to `LocaleController`'s `applyLanguage` function, specifically where it overrides the current locale. I can't really check for myself because CupertinoLib is not public.

**Comment by ctwoon** [comment]
You're using google play build? Please check out build from telegram channel (t.me/catogram) as gp build kinda outdated.

**Comment by Raymonf** [comment]
@ctwoon I switched to the latest channel build but:

1. I don't see the system font toggle anymore.
2. The same issue is present.

**Comment by ctwoon** [comment]
@Raymonf 
1. I've removed Roboto fonts from application. Now it uses system font by default. 
2. Please send screenshots of current and expected results.

**Comment by Raymonf** [comment]
@ctwoon 

I'm using the localization from https://t.me/localization_hk (tg://setlanguage?lang=hongkong). I think the issue is only present with zh-* custom locales.

---

Current (Catogram, zh-CN glyphs instead of zh-HK):

![photo_2021-02-23_19-45-34](https://user-images.githubusercontent.com/8991740/108928168-c2d10f80-760f-11eb-9a1e-ca1f933a4e43.jpg)

Expected (Telegram X, zh-HK glyphs):

![photo_2021-02-23_19-45-36](https://user-images.githubusercontent.com/8991740/108928171-c4023c80-760f-11eb-8d38-85f637e5bde9.jpg)

(notice this 入:)
![image](https://user-images.githubusercontent.com/8991740/108928381-12afd680-7610-11eb-8ecd-8c5c8d49cd51.png)

**Comment by ctwoon** [comment]
ok, I'll see what I can do.

**Comment by Raymonf** [comment]
Thanks!

在 2021年2月24日週三 上午2:50，Nick C <notifications@github.com> 寫道：

**Comment by ctwoon** [comment]
reopen if issue still persists
