### ISSUE TITLE
The translation function cannot specify the translation language

### ISSUE THREAD

**Issue by blackblue-q** [Catogram/Catogram#65]
I hope to add a switch to select the translation language and request Chinese adaptation.

**Comment by ctwoon** [comment]
I have no plans to add such a feature. What problems are you experiencing with the translation?

**Comment by blackblue-q** [comment]
I want to translate other languages ​​into Chinese

**Comment by ctwoon** [comment]
@blackblue-q 

in that case your telegram locale must be Chinese.

**Comment by blackblue-q** [comment]
I set the telegram language to Chinese, but the translation function only translates to English

**Comment by ctwoon** [comment]
please try this version

http://bashupload.com/3-Rbd/app.apk
