### ISSUE TITLE
hide message if user is blocked

### ISSUE THREAD

**Issue by zanisdifferent** [Catogram/Catogram#74]
This function does not work usually,please fix it,thanks very much.(I think you can add that purple icon into the choices for app,just for beauty)

**Comment by ctwoon** [comment]
it works for me, more information is needed.

**Comment by zanisdifferent** [comment]
> 
> 
> it works for me, more information is needed.

it work from time to time,not always useless

**Comment by ctwoon** [comment]
1.what does it mean from time to time?
2.what version are you on?

**Comment by zanisdifferent** [comment]
> 
> 
> 1.what does it mean from time to time?
> 2.what version are you on?

the latest version

when I open this function,it just work,but when I open it again,it might does not work successfully.I make sure that I blocked that user,and turn on this function,but I still can watch his messages.

**Comment by zanisdifferent** [comment]
> 
> 
> 1.what does it mean from time to time?
> 2.what version are you on?

hello,I have a try for the latest version,this problem has been solved.but I have to block them again,the function still  is useless for the person blocked before.

**Comment by ctwoon** [comment]
do not block, but a single visit to their profile is a must.

**Comment by zanisdifferent** [comment]
> 
> 
> do not block, but a single visit to their profile is a must.

ohh,I find it that if I visit to their profile,the function works,but if I stop app,and restart it again,it will not work successfully again.then I visit their profile again,it works.can you improve it?thank you very much!
